server:
  port: 8080

spring:
  application:
    name: semantic-search-api

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ecommerce_search}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin123}

# Custom configuration
embedding:
  service:
    url: ${EMBEDDING_SERVICE_URL:http://localhost:8000}

api:
  key: ${API_KEY:your-secret-api-key-here}

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.ecommerce.search: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE